[tool.ruff]
target-version = "py312"
line-length = 88
indent-width = 4
fix = true
exclude = ["build", "dist", ".venv", ".mypy_cache", ".ruff_cache"]

select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "B",   # bugbear
    "I",   # isort
    "UP",  # pyupgrade
    "N",   # pep8-naming
]

[tool.black]
line-length = 88
target-version = ["py312"]
exclude = '''
/(
    \.venv
  | build
  | dist
)/
'''
